server:
  port: 8761
  
spring:
  profiles:
    active: node1
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://demo.eureka.com:8762/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: true

---

server:
  port: 8762
  
spring:
  profiles:
    active: node2
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://demo.eureka.com:8762/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10
    hostname: demo.eureka.com
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: true